Handle data_callback errors and signal to user via state_callback.
djg/cubeb-pulse-rs pull request #79
Opened 2022-03-28 23:39 UTC by kinetiknz

See https://github.com/mozilla/cubeb/pull/698

2022-03-29 11:47 UTC, padenot approved these changes

2022-03-29 17:24 UTC, ChunMinChang requested changes
LGTM!

I only need to confirm if we need to fire an error callback when user returns a less-than-nframes value.

2022-03-29 17:24 UTC, ChunMinChang commented on src/backend/stream.rs
> +                            }
```suggestion
                            if got < 0 {
                                unsafe {
                                    stm.state_callback.unwrap()(
                                        stm as *mut _ as *mut _,
                                        stm.user_ptr,
                                        ffi::CUBEB_STATE_ERROR,
                                    );
                                }
                            }
```

From https://github.com/mozilla/cubeb/blob/d97fea4c9015b5d79e11ad68e9cdac610c27ca07/include/cubeb/cubeb.h#L418-L420:
> If the stream is input only, then returning nframes indicates data has been read. In this case, a value less than nframes will result in the stream being stopped.

This will fire error callback when user return a less than nframes value (`got as usize != read_frames`) as well. I think we should fire error callback only if `got < 0`, as what cubeb_wasapi.cpp does?

2022-03-30 05:11 UTC, kinetiknz commented on src/backend/stream.rs
> +                            }
Good catch, thanks! I've fixed this in cubeb_pulse.c also.

2022-03-30 05:12 UTC, merged